### ISSUE TITLE
Clarify License

### ISSUE THREAD

**Issue by xmj** [Twinuma/terraform-waf-owasp#4]
Hi @Twinuma,

Could you please clarify the license terms under which we may use the terraform module?

I would propose to use something comparable to MIT/ISC License, in line with the [Copyfree Initiative](http://copyfree.org/standard)'s standard.

Thanks,
Johannes

**Comment by helloworlddan** [comment]
+1
Could you please attach a license to the module, @Twinuma

**Comment by Twinuma** [comment]
I don't know how to set it up, if possible, would you make a PR? I'll merge it.

**Comment by xmj** [comment]
I've added a pull request using the  [MIT license](https://opensource.org/licenses/MIT), and your name. Hope this works for you!
